name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - init

jobs:
  build_image:
    name: Build ${{ matrix.platform }} image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          # - linux/arm/v7
          - linux/arm64
          - linux/s390x
          - linux/ppc64le
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.platform }} image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          load: true
          push: false
          tags: manylinux_2_35:latest
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}

      - name: Test ${{ matrix.platform }} image
        run: docker run --rm -v $(pwd)/tests:/tests:ro manylinux_2_35:latest /tests/run_tests.sh
